name: Daily Electronics Scraping

# Run automatically every day at 6:00 AM UTC (9:00 AM Jordan time)
on:
  schedule:
    - cron: '0 6 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  scrape-electronics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run daily scraping orchestrator
      run: |
        echo "Starting daily electronics scraping..."
        python daily_scraper.py
      
    - name: Check scraping results
      run: |
        echo "Checking if logs directory was created..."
        if [ -d "logs" ]; then
          echo "✅ Logs directory found"
          ls -la logs/
          echo "📊 Latest log content:"
          find logs -name "*.log" -type f -exec tail -20 {} \;
        else
          echo "⚠️ No logs directory found"
        fi
        
    - name: Upload scraping logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: scraping-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
        
    - name: Summary report
      if: always()
      run: |
        echo "📊 DAILY SCRAPING SUMMARY"
        echo "=========================="
        echo "Date: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow run: ${{ github.run_number }}"
        echo "Status: ${{ job.status }}"
        echo "Check the uploaded artifacts for detailed logs."